// All site copy lives here. Edit this file, not app.js.
export const CONTACT_EMAIL = 'ma@yarray.com.au';

export const routes = {
  '/': {
    nav: 'Home',
    title: 'YarraY — AI software solutions & services',
    blocks: [
      { type: 'hero',
        eyebrow: 'AI software consultancy · Australia',
        heading: 'AI software that holds up in production.',
        sub: 'YarraY helps Australian organisations design, build, and operate AI systems their teams can rely on — with the evaluation, guardrails, and cost discipline that keep them running after launch.',
        cta: { label: 'Discuss a project', href: '#/contact' } },

      { type: 'cards',
        eyebrow: 'Capabilities',
        heading: 'What we do',
        items: [
          { h: 'AI strategy & discovery',
            p: 'Short, focused engagements that identify where AI will repay the investment in your business — and where it will not. You finish with a costed shortlist and a written recommendation.' },
          { h: 'Custom AI applications',
            p: 'Assistants, document processing, retrieval over your own content, and bounded agent workflows — built against your systems, with evaluation and access controls designed in from the start.' },
          { h: 'AI inside existing products',
            p: 'We add AI capability to software you already run. Your authentication, data model, and deployment pipeline stay as they are; no rewrite, no parallel stack.' },
          { h: 'Data & platform engineering',
            p: 'The pipelines, indexing, and infrastructure beneath the model. A large share of stalled AI projects stall here, which is why we start here.' },
          { h: 'Evaluation & reliability',
            p: 'Testing for non-deterministic systems: labelled benchmark sets, regression checks on every change, and explicit accuracy, latency, and cost budgets.' },
          { h: 'Operations & support',
            p: 'Models are deprecated, prompts drift, and unit costs move. We stay engaged to keep what we built performing as the ground shifts beneath it.' },
        ] },

      { type: 'steps',
        eyebrow: 'Engagement',
        heading: 'How a project runs',
        items: [
          { h: 'Discovery',
            p: 'One to two weeks. We map the workflow, the data, and the constraints with the people who do the work, then define what "working" means as a measurable threshold.' },
          { h: 'Proof of concept',
            p: 'A narrow build against your real data, scored against the thresholds agreed in discovery. If the results do not clear the bar, we report that plainly rather than proceeding.' },
          { h: 'Production build',
            p: 'Delivered in increments you can use, with monitoring, an evaluation suite, documentation, and deployment into your own cloud accounts.' },
          { h: 'Handover or support',
            p: 'Code, tests, and runbooks are yours either way. Retain us for ongoing work or take it in-house — the build is designed so both are viable.' },
        ] },

      { type: 'prose',
        eyebrow: 'Why teams engage us',
        heading: 'Most AI work fails between the demo and production',
        body: [
          'A model that performs well in a notebook still has to meet real data, real permissions, real users, and a real cost ceiling. That transition is where most pilots quietly end.',
          'We are software engineers before we are anything else. The parts that decide whether an AI feature survives contact with a business — data access, failure handling, evaluation, cost per request, and who is accountable when the answer is wrong — are the parts we treat as the actual project.',
          'We also work in the open. You see the repository, the evaluation results, and the running costs throughout, not in a final report.',
        ] },

      { type: 'band',
        heading: 'Considering an AI project?',
        body: 'A first conversation is thirty minutes and costs nothing. You will get a direct view on whether the problem suits AI, roughly what it would take, and what could go wrong.',
        cta: { label: 'Get in touch', href: '#/contact' } },
    ],
  },

  '/services': {
    nav: 'Services',
    title: 'Services — YarraY',
    blocks: [
      { type: 'prose',
        lead: true,
        eyebrow: 'Services',
        heading: 'Scoped tightly, priced up front',
        body: [
          'Most engagements begin with a discovery sprint, so both sides understand what is being committed to before anyone commits to a build.',
          'Work is grouped into three stages — decide, build, and run. Clients engage us for one stage or all three.',
        ] },

      { type: 'cards',
        eyebrow: 'Stage one',
        heading: 'Decide',
        items: [
          { h: 'Opportunity mapping',
            p: 'We interview the people performing the work, observe the process as it actually runs, and identify where an AI system would remove meaningful hours rather than add risk.' },
          { h: 'Feasibility assessment',
            p: 'Data readiness, integration surface, privacy and residency constraints, and a defensible cost per transaction — established before you fund a build.' },
          { h: 'Costed roadmap',
            p: 'A sequenced plan with effort, dependencies, and expected return for each item, ordered so the first delivery is the one that pays for the next.' },
        ] },

      { type: 'cards',
        eyebrow: 'Stage two',
        heading: 'Build',
        items: [
          { h: 'Retrieval over your own data',
            p: 'Question answering and search across documents, tickets, contracts, and knowledge bases — with citations, and access that respects the permissions your systems already enforce.' },
          { h: 'Document & form processing',
            p: 'Extraction, classification, and validation for invoices, applications, claims, and compliance paperwork, with human review placed where the cost of an error justifies it.' },
          { h: 'Agent workflows',
            p: 'Multi-step automation that calls your APIs and tools within a bounded scope, with audit trails and explicit stopping conditions rather than open-ended autonomy.' },
          { h: 'Customer-facing assistants',
            p: 'Support and sales assistants grounded in your own content, with escalation paths, refusal behaviour, and a tone your brand can stand behind.' },
          { h: 'Internal tooling',
            p: 'The unglamorous internal applications that return a team several hours a week and rarely survive a roadmap prioritisation on their own.' },
          { h: 'Model selection & integration',
            p: 'Provider-agnostic. We select for accuracy, latency, cost, and data-residency requirements, and structure the code so the provider can be changed later without a rewrite.' },
        ] },

      { type: 'cards',
        eyebrow: 'Stage three',
        heading: 'Run',
        items: [
          { h: 'Evaluation harnesses',
            p: 'Automated scoring against labelled cases, run on every change, so a prompt edit or model upgrade cannot quietly degrade quality unnoticed.' },
          { h: 'Monitoring & cost control',
            p: 'Reporting on accuracy, latency, spend, and failure modes, with alerting thresholds set before launch rather than after the first incident.' },
          { h: 'Support & iteration',
            p: 'Retainer or block-of-hours arrangements covering maintenance, provider migrations, and new capability as the system earns further investment.' },
        ] },

      { type: 'faq',
        eyebrow: 'Common questions',
        heading: 'Before you enquire',
        items: [
          { q: 'How are engagements priced?',
            a: 'Discovery sprints and proofs of concept are fixed price against a written scope. Production builds are quoted per increment once discovery has removed the major unknowns. Ongoing support is a monthly retainer or a block of hours. We do not quote a production build before discovery, because any number given at that point would be a guess.' },
          { q: 'How long does a first project take?',
            a: 'Discovery is one to two weeks. A proof of concept is typically two to six weeks depending on data access. A first production increment usually lands six to twelve weeks after that. Data access and stakeholder availability move these dates more than engineering does.' },
          { q: 'Where does our data go?',
            a: 'That is decided explicitly with you during discovery and documented. We can work entirely within your cloud tenancy and with Australian data residency where your obligations require it, and we will tell you plainly when a requirement rules out a particular model or provider.' },
          { q: 'Do we end up locked in to you?',
            a: 'No. Work is delivered in standard languages into your repository and your cloud accounts, with documentation and tests. Model providers are swappable by design. If you choose to take the system in-house, that should be a handover, not a migration project.' },
          { q: 'What if AI is not the right answer?',
            a: 'We will say so. A rules engine, a redesigned form, or a database query solves a fair number of the problems that arrive described as AI projects. Recommending one of those costs us a build and saves you a system you would have had to maintain.' },
          { q: 'Do you work with small organisations?',
            a: 'Yes. Scope is what matters, not headcount. A well-defined problem at a twenty-person firm is a better engagement than an undefined one at an enterprise.' },
        ] },

      { type: 'band',
        heading: 'Tell us what you are trying to improve',
        body: 'Describe the workflow and what it costs you today. We will tell you whether it is a fit and what the first stage would involve.',
        cta: { label: 'Contact YarraY', href: '#/contact' } },
    ],
  },

  '/approach': {
    nav: 'Approach',
    title: 'Approach — YarraY',
    blocks: [
      { type: 'prose',
        lead: true,
        eyebrow: 'Approach',
        heading: 'AI systems fail differently',
        body: [
          'Conventional software fails loudly. It throws an exception, the request returns a 500, and someone is paged. An AI system fails by returning a fluent, confident, wrong answer that nobody catches until it has been acted on.',
          'That single difference drives the way we scope, build, and hand over every project.',
        ] },

      { type: 'cards',
        eyebrow: 'Principles',
        heading: 'How we build',
        items: [
          { h: 'Define "working" as a number',
            p: 'Before any build begins we agree the accuracy, latency, and cost thresholds that make the system worth operating. Without a threshold, "it seems good in the demo" becomes the acceptance test by default.' },
          { h: 'The smallest useful scope',
            p: 'One workflow done properly outperforms a platform that half-covers six. Narrow scope is also the only honest basis on which to quote fixed-price work.' },
          { h: 'Your data stays yours',
            p: 'We operate within your privacy, residency, and retention obligations, and we document precisely what leaves your environment, where it goes, and how long it is retained.' },
          { h: 'Nothing that requires us',
            p: 'Standard languages, your cloud account, your repository, provider-agnostic interfaces. Continuing with us should be a commercial decision, never a technical necessity.' },
          { h: 'A person decides what matters',
            p: 'Where a decision carries legal, financial, or safety weight, the system recommends and a person decides. We place that boundary deliberately at design time rather than adding it after an incident.' },
          { h: 'Honest reporting',
            p: 'Evaluation results, known failure modes, and running costs are shared as they are, including the unflattering ones. A number you cannot trust is worse than no number.' },
        ] },

      { type: 'prose',
        eyebrow: 'Your side',
        heading: 'What we need from you',
        body: [
          'Access to someone who does the work today — not only a project sponsor, but the person whose afternoon the system is intended to give back.',
          'Sample data with its faults intact. Cleaned samples conceal exactly the failure modes we are being engaged to handle.',
          'A view on what a wrong answer costs. That figure determines how much review, evaluation, and guardrail the build warrants, and it is the single most useful thing you can bring to the first meeting.',
          'A decision-maker who can approve scope. AI projects lose more time to unresolved scope than to unresolved engineering.',
        ] },

      { type: 'band',
        heading: 'Read something you disagree with?',
        body: 'Good — that is a useful first conversation. We would rather work through a disagreement before an engagement than during one.',
        cta: { label: 'Start the conversation', href: '#/contact' } },
    ],
  },

  '/about': {
    nav: 'About',
    title: 'About — YarraY',
    blocks: [
      { type: 'prose',
        lead: true,
        eyebrow: 'About',
        heading: 'A small senior team, by design',
        body: [
          'YarraY is an Australian AI software consultancy. We build AI systems for organisations that need them to work in production rather than to appear in an announcement.',
          'We stay small on purpose. The people who scope your project are the people who write the code, so nothing is lost between the first conversation and the delivery, and there is no layer of account management between you and the engineers.',
          'Our background is in software engineering, data platforms, and applied machine learning. We have seen enough AI initiatives fail for structural reasons — unclear success criteria, inaccessible data, no owner after launch — to be direct with clients about what will and will not succeed.',
          'We work with organisations across Australia, remotely by default and on site where proximity genuinely helps.',
        ] },

      { type: 'cards',
        eyebrow: 'Working with us',
        heading: 'What to expect',
        items: [
          { h: 'Fixed scope, fixed price',
            p: 'Where work can be specified, it is quoted before it starts. An unexpected number on an invoice is our estimating problem, not your budget problem.' },
          { h: 'Plain English throughout',
            p: 'No deck of jargon. If a design decision cannot be explained to a non-technical stakeholder in a sentence or two, we treat that as a sign the decision is not yet good enough.' },
          { h: 'Built to be handed over',
            p: 'Documented, tested, and running in your own accounts from the first increment, so a handover is a conversation rather than a project.' },
          { h: 'Direct answers',
            p: 'Including when the answer is that the project should not proceed, that the timeline is unrealistic, or that the budget does not match the ambition.' },
        ] },

      { type: 'band',
        heading: 'Work with YarraY',
        body: 'We take on a small number of engagements at a time. If the fit is right, we will tell you quickly; if it is not, we will say that just as quickly.',
        cta: { label: 'Enquire about availability', href: '#/contact' } },
    ],
  },

  '/contact': {
    nav: 'Contact',
    title: 'Contact — YarraY',
    blocks: [
      { type: 'contact',
        eyebrow: 'Contact',
        heading: 'Start a conversation',
        body: 'Tell us the workflow you are trying to improve and what it costs you today. The first call runs thirty minutes, costs nothing, and ends with a straight answer on whether AI is the right tool for the problem.',
        email: CONTACT_EMAIL },

      { type: 'prose',
        eyebrow: 'Enquiries',
        heading: 'Useful things to include',
        body: [
          'The process or decision you want to improve, and who performs it today.',
          'What the relevant data looks like, roughly how much of it there is, and which system it lives in.',
          'Any deadline, budget range, or compliance obligation we should know about up front.',
          'Whether you have already attempted something in this area, and what happened.',
        ] },

      { type: 'prose',
        eyebrow: 'Response times',
        heading: 'What happens next',
        body: [
          'We reply to enquiries within two business days.',
          'If the problem is outside what we do well, we will say so and, where we can, point you toward someone better suited to it.',
        ] },
    ],
  },
};
